server:
  port: 80
spring:
  application:
    name: sample
  datasource:
    name: sample
    url: jdbc:postgresql://${DB_SERVER_IP}:${DB_SERVER_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    druid: 
      filters: stat
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20        
mybatis:
  mapper-locations: 
    - /com/hngd/mapping/*.xml
  type-aliases-package: com.hngd.model 
eureka:
  client:
    service-url:
      defaultZone: ${REGISTER_CENTER}
  instance:
    prefer-ip-address: true
logging:
   config: ./config/log4j2-docker.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
hnvmns: 
  web: 
    pagehelper: 
      enable: true
operation:
  log: 
    systemName: sample
    handlerThreadCount: 2

   
        